name: Terraform CI/CD Demo (No Cloud)

on:
  push:
    branches:
      - cicd-demo

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Authenticate to GCP
      run: |
        echo '${{ secrets.GCP_CREDENTIALS }}' > service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS="service-account.json"
        gcloud auth activate-service-account --key-file=service-account.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Test GCS access
      run: |
        gsutil ls gs://${{ secrets.GCP_BUCKET_NAME }}

    - name: Terraform Init
      run: |
          terraform init \
          -backend-config="bucket=${{ secrets.GCP_BUCKET_NAME }}" \
          -backend-config="prefix=terraform/state"

    - name: Terraform Apply
      run: terraform apply -auto-approve

# # 2. Set up Google Cloud authentication
# - name: 🔑 Authenticate with Google Cloud
#   uses: google-github-actions/auth@v2
#   with:
#     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'  # ใช้ Secret ที่เก็บไฟล์ JSON

# # 3. ตรวจสอบว่า authentication สำเร็จไหม
# - name: 🧪 Who am I?
#   run: |
#     gcloud auth list

# # 4. ทดสอบการเข้าถึง GCS ด้วย gsutil
# - name: 📤 Test GCS access with gsutil
#   run: |
#     gsutil ls gs://ci-cd_for_test/
#
#