name: 🔁 Test GCS Upload

on:
  workflow_dispatch:  # กดรันด้วยมือในหน้า Actions ได้

jobs:
  upload-test:
    runs-on: ubuntu-latest

    steps:
    - name: 📄 Create test file
      run: echo "this is a test" > hello.txt

    - name: 🔑 Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 📤 Upload to GCS
      run: |
        FILE_NAME="hello-$(date +%s).txt"
        echo "Uploading $FILE_NAME"
        gsutil cp hello.txt gs://raw_zone_mongodb/$FILE_NAME
