name: Terraform CI/CD Demo (No Cloud)

on:
  push:
    branches:
      - cicd-demo

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: 📤 Test GCS access with gsutil
  run: |
    gsutil ls gs://ci-cd_for_test/
